### ISSUE TITLE
Merge factory defaults of pipeline steps with project-specific config

### ISSUE THREAD

**Issue by Nayjest** [Nayjest/Gito#97]
This will allow to do stuff like following in project config:
```toml
[pipeline_steps.jira]
enabled=false
```
(not necessary to file all required fields just to disable it)

Details:
1. Merge PipelineStep fields
2. Merge Pipeline dict by itself (!)
